Address comments
Signed-off-by: Connor Roos <croos@nvidia.com>

diff --git a/platform/nvidia-bluefield/installer/install.sh.j2 b/platform/nvidia-bluefield/installer/install.sh.j2
--- a/platform/nvidia-bluefield/installer/install.sh.j2
+++ b/platform/nvidia-bluefield/installer/install.sh.j2
@@ -99,14 +99,22 @@ if [ -e /etc/bf.cfg ]; then
 	. /etc/bf.cfg
 fi
 
-if [ -n "$NPU_TIME" ]; then
+if [[ "$NPU_TIME" =~ ^[0-9]+$ ]]; then
 	log "Setting system time from NPU: $NPU_TIME"
-	date -s "@$NPU_TIME"
-	log "System time set to: $(date)"
-	if [ -e /dev/rtc0 ]; then
-		hwclock --systohc --utc
-		log "Hardware clock synced from system time"
+	if date -s "@$NPU_TIME" > /dev/null 2>&1; then
+		log "System time set to: $(date)"
+		if [ -e /dev/rtc0 ]; then
+			if hwclock --systohc --utc > /dev/null 2>&1; then
+				log "Hardware clock synced from system time"
+			else
+				log "WARNING: Failed to sync hardware clock from system time (rc=$?)"
+			fi
+		fi
+	else
+		log "WARNING: Failed to set system time from NPU_TIME=$NPU_TIME (rc=$?)"
 	fi
+else
+	log "Invalid NPU_TIME value '$NPU_TIME'; expected positive integer Unix timestamp. Skipping time update."
 fi
 
 # Flags that can be overwritten by the bf.cfg
