[Arista] Ignore error from readprefdl
Booting may be blocked due to readprefdl errors on prototype platforms or
devices with hardware issues. To improve debuggability on these systems,
we want to ignore these errors and allow the boot process to continue.

Signed-off-by: Boyang Yu <byu@arista.com>

diff --git a/files/Aboot/boot0.j2 b/files/Aboot/boot0.j2
--- a/files/Aboot/boot0.j2
+++ b/files/Aboot/boot0.j2
@@ -465,7 +465,8 @@ EOF
 
 read_eeprom() {
     if [ -x /bin/readprefdl ] && [ -f "$1" ]; then
-        readprefdl -f "$1" -d > $target_path/.system-prefdl
+        readprefdl -f "$1" -d > $target_path/.system-prefdl || err "Failed on readprefdl -f $1 -d"
+
     elif [ -f /etc/prefdl ]; then
         cp /etc/prefdl $target_path/.system-prefdl
         chmod a+r $target_path/.system-prefdl
