fix(p4rt): Consume new version of sonic-swss-common
Signed-off-by: Borja Lorente <blorente.me@gmail.com>

diff --git a/src/sonic-p4rt/Makefile b/src/sonic-p4rt/Makefile
--- a/src/sonic-p4rt/Makefile
+++ b/src/sonic-p4rt/Makefile
@@ -11,6 +11,14 @@ BAZEL_BUILD_OPTS += --copt=-gsplit-dwarf
 # Override sonic_swss_common to use the version specific to this buildimage.
 BAZEL_BUILD_OPTS += --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common
 
+# sonic-swss-common cannot generate cfg_schema.h under Bazel yet,
+# so we hand it the real YANG-generated one that libswsscommon-dev installs (staged into CFG_SCHEMA_REPO below).
+# This keeps YANG modules enabled, so p4rt links the same libswsscommon it always has.
+CFG_SCHEMA_H = /usr/include/swss/cfg_schema.h
+CFG_SCHEMA_REPO = /tmp/sonic-p4rt-cfg-schema
+BAZEL_BUILD_OPTS += --override_repository=swss_cfg_schema=$(CFG_SCHEMA_REPO)
+BAZEL_BUILD_OPTS += --@sonic_swss_common//tools/bazel:cfg_schema=@swss_cfg_schema//:cfg_schema.h
+
 # Newer version of gcc has spurious warnings in boringssl package.
 BAZEL_BUILD_OPTS += --copt=-Wno-array-bounds
 BAZEL_BUILD_OPTS += --copt=-Wno-stringop-overflow
@@ -33,21 +41,26 @@ BAZEL_OPTS += $(shell test -d $(BAZEL_CACHE) && echo --output_user_root=$(BAZEL_
 MAIN_TARGET = $(SONIC_P4RT)
 DERIVED_TARGETS = $(SONIC_P4RT_DBG)
 
-$(addprefix $(DEST)/, $(MAIN_TARGET)): $(DEST)/% :
+# TODO: Remove this Makefile workaround once Bazel supports generating cfg_schema.h.
+#
+# Wrap the installed header in a throwaway repository, so that it can be named by a label
+# and handed to --@sonic_swss_common//tools/bazel:cfg_schema.
+$(CFG_SCHEMA_REPO)/BUILD: $(CFG_SCHEMA_H)
+	mkdir -p $(@D)
+	cp $< $(@D)/cfg_schema.h
+	echo 'workspace(name = "swss_cfg_schema")' > $(@D)/WORKSPACE
+	echo 'exports_files(["cfg_schema.h"])' > $@
+
+$(CFG_SCHEMA_H):
+	echo "$@ not found: is libswsscommon-dev installed?" >&2
+	exit 1
+
+$(addprefix $(DEST)/, $(MAIN_TARGET)): $(DEST)/% : $(CFG_SCHEMA_REPO)/BUILD
 	function cleanup {
 		# Note: make seems to hang if Bazel is still running
 		cd $(CURDIR)/sonic-pins && bazel $(BAZEL_OPTS) shutdown
 	}
 	trap cleanup EXIT
-
-	# TODO: Remove this Makefile workaround
-	# once Bazel natively supports generating cfg_schema.h.
-	if [[ ! -f /sonic/src/sonic-swss-common/common/cfg_schema.h && -f /usr/include/swss/cfg_schema.h ]]; then \
-		if [ ! -d /sonic/src/sonic-swss-common/common ]; then \
-			mkdir -p /sonic/src/sonic-swss-common/common; \
-		fi; \
-		cp /usr/include/swss/cfg_schema.h /sonic/src/sonic-swss-common/common/cfg_schema.h; \
-	fi
 
 	pushd ./sonic-pins
 	bazel $(BAZEL_OPTS) build $(BAZEL_BUILD_OPTS) $(BAZEL_BUILD_TARGETS)
