Merged PR 7843446: [internal][cherry-pick]Check in vnet-monitor docker
This PR is to backport PR!7770531 into internal branch.

diff --git a/.pipelines/OneBranch.OfficialBuild.yml b/.pipelines/OneBranch.OfficialBuild.yml
--- a/.pipelines/OneBranch.OfficialBuild.yml
+++ b/.pipelines/OneBranch.OfficialBuild.yml
@@ -231,7 +231,7 @@ stages:
           script: |
             set -ex
             OPTIONS="$(BUILD_OPTIONS) SONIC_DPKG_CACHE_METHOD=wcache PASSWORD=$PASSWORD"
-            make $OPTIONS target/sonic-mellanox.bin
+            make $OPTIONS INCLUDE_VNET_MONITOR=y target/sonic-mellanox.bin
             make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-mlnx-rpc.gz
             cp target/debs/bullseye/python-saithrift_0.9.4_amd64.deb target/python-saithrift_0.9.4_amd64.deb
         - name: barefoot
@@ -249,3 +249,63 @@ stages:
           script: |
             OPTIONS="$(BUILD_OPTIONS) PASSWORD=$PASSWORD"
             make $OPTIONS target/sonic-marvell-armhf.bin
+        - name: cisco-8000
+          variables:
+            TERM: ''
+          steps:
+          - script: |
+              cisco_ref=$(cat platform/checkout/cisco-8000.ini | grep '^ref=' | cut -d= -f2)
+              echo "The cisco 8000 release version is $cisco_ref"
+              echo "##vso[task.setvariable variable=cisco.ref]$cisco_ref"
+            displayName: 'Export cisco release version'
+          - task: DownloadGitHubRelease@0
+            inputs:
+              connection: cisco-connection
+              userRepository: Cisco-8000-sonic/platform-cisco-8000
+              defaultVersionType: specificTag
+              version: $(cisco.ref)
+              itemPattern: 'artifactory-*.tar.gz'
+              downloadPath: '$(System.ArtifactsDirectory)'
+          - script: |
+              tar xvfz $(System.ArtifactsDirectory)/artifactory-*.tar.gz -C platform/cisco-8000
+            displayName: 'Setup cisco artifacts'
+          - script: |
+              if [ ! -e platform/cisco-8000/device/x86_64-8102_64h_o-r0/Cisco-8102-C64 ]; then
+                echo "hwsku Cisco-8102-C64 doesn't exist, copy from 64x100Gb"
+                cp -r platform/cisco-8000/device/x86_64-8102_64h_o-r0/64x100Gb platform/cisco-8000/device/x86_64-8102_64h_o-r0/Cisco-8102-C64
+              else
+                echo "hwsku Cisco-8102-C64 exist"
+              fi
+            displayName: 'Setup cisco hwsku Cisco-8102-C64'
+          - script: |
+              set -ex
+              filename=$(find platform/cisco-8000/artifactory/sonic -name cisco-* -type f | head -n 1)
+              if [ -z "$filename" ]; then
+                echo "Cisco sai package not found" 1>&2
+                exit 1
+              fi
+              cd $(dirname $filename)
+              echo "PWD=$(pwd)"
+              ls -l cisco-*.deb
+              while read -r package; do
+                # Cisco version format: <VERSION>-sai-<sai-ver>-<distribution>-<COMMIT HASH>
+                # The <sai-ver> may contain several values in one build, the part is skipped when publishing to storage
+                # See https://github.com/Cisco-8000-sonic/sdk/blob/master/azure-pipelines.yml
+                # The $PACKAGE_URL is only accessible for AZP
+                version=$(echo $package | awk -F_ '{print $(NF-1)}' | cut -d- -f1,2,4,5)
+                package_url="$PACKAGE_URL/sai/ciscosai/master/$version/$package"
+                echo "Override package $package from $package_url"
+                wget "$package_url$StorageSASKey" -O "$package"
+              done < <(ls cisco-*.deb)
+            env:
+              StorageSASKey: $(SONIC_PUBLIC_STORAGE_SASKEY)
+            condition: ne(variables['Build.Reason'], 'PullRequest')
+            displayName: "Override cisco sai packages"
+          - script: |
+              set -ex
+              OPTIONS="$(BUILD_OPTIONS) ENABLE_NAT=n INCLUDE_RESTAPI=y INCLUDE_VNET_MONITOR=y PASSWORD=$PASSWORD"
+              make $OPTIONS target/sonic-cisco-8000.bin
+              make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-cisco-rpc.gz
+            env:
+              PASSWORD: '$(PASSWORD)'
+            displayName: JobScript
