Merged PR 12190218: [ci] Add log scan step to detect reproducible build fall back cases.
[ci] Add log scan step to detect reproducible build fall back cases.

----
#### AI description  (iteration 1)
#### PR Classification
New feature

#### PR Summary
This pull request adds a log scan step to detect reproducible build fallback cases in the CI pipeline.
- `/.pipelines/template-stages.yml`: Redirect build output to log files for various targets.
- `/.pipelines/template-poststeps.yml`: Add log scan step to check for errors in build logs.
- `/.pipelines/template-cisco.yml`: Redirect build output to log files for Cisco targets.
<!-- GitOpsUserAgent=GitOps.Apps.Server.pullrequestcopilot -->

diff --git a/.pipelines/template-poststeps.yml b/.pipelines/template-poststeps.yml
--- a/.pipelines/template-poststeps.yml
+++ b/.pipelines/template-poststeps.yml
@@ -15,6 +15,15 @@ parameters:
     default: 'default'
 
 steps:
+  - script: |
+      set -ex
+      logfiles=$(find target/ -name *.log)
+      if grep -B 20 -e "Err:" -e "Failed to run the command with constraint, try to install with the original command" $logfiles; then
+        exit 1
+      fi
+      exit 0
+    continueOnError: true
+    displayName: Log Scan
   - ${{ if eq(variables['Build.DefinitionName'], 'Networking-acs-buildimage-Official-OneBranch') }}:
     # Only enable BinSkim on VS platform, because they share same way of compiling
     # Only enable on VS platform can maximum reduce the affection to current build logic
