[Test] p4rt
Signed-off-by: Sreemoolanathan Iyer <sbiyer@google.com>

diff --git a/.azure-pipelines/azure-pipelines-build.yml b/.azure-pipelines/azure-pipelines-build.yml
--- a/.azure-pipelines/azure-pipelines-build.yml
+++ b/.azure-pipelines/azure-pipelines-build.yml
@@ -144,13 +144,31 @@ jobs:
           if [ $(GROUP_NAME) == pensando ]; then
             make $BUILD_OPTIONS target/sonic-pensando.tar
           elif [ $(GROUP_NAME) == vs ]; then
+
+            pwd
+            ls -lh ../ || true
+            ls -lh ./  || true
+            ls -lh src || true
+            ls -lh src/sonic-p4rt || true
+            ls -lh src/sonic-swss-common/common | grep cfg || true
+            # cat src/sonic-p4rt/Makefile
+
+            # sed -i 's|trap cleanup EXIT|trap cleanup EXIT\n\tif [ ! -f /sonic/src/sonic-swss-common/common/cfg_schema.h ] \&\& [ -f /usr/include/swss/cfg_schema.h ]; then\n\t\tcp /usr/include/swss/cfg_schema.h /sonic/src/sonic-swss-common/common/cfg_schema.h\n\tfi|' src/sonic-p4rt/Makefile
+
+            sed -i 's|trap cleanup EXIT|trap cleanup EXIT\n\tif [ ! -f /sonic/src/sonic-swss-common/common/cfg_schema.h ] \&\& [ -f /usr/include/swss/cfg_schema.h ]; then\n\t\tcp /usr/include/swss/cfg_schema.h /sonic/src/sonic-swss-common/common/cfg_schema.h\n\t\ttouch /sonic/src/sonic-swss-common/common/cfg-found\n\telif [ -f /sonic/src/sonic-swss-common/common/cfg_schema.h ]; then\n\t\ttouch /sonic/src/sonic-swss-common/common/cfg-found\n\telse\n\t\ttouch /sonic/src/sonic-swss-common/common/cfg-not-found\n\tfi|' src/sonic-p4rt/Makefile
+
+            sed -i 's|trap cleanup EXIT|trap cleanup EXIT\n\t(cd sonic-pins \&\& bazel $(BAZEL_OPTS) info output_base \|\| true)|' src/sonic-p4rt/Makefile
+
+            # cat src/sonic-p4rt/Makefile
+
             if [ $(dbg_image) == yes ]; then
-              make $BUILD_OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-vs.img.gz
-              mv target/sonic-vs.img.gz target/sonic-vs-dbg.img.gz
+              make $BUILD_OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-vs.img.gz || true
+              mv target/sonic-vs.img.gz target/sonic-vs-dbg.img.gz || true
             fi
             if [ $(asan_image) == yes ]; then
-              make $BUILD_OPTIONS ENABLE_ASAN=y target/docker-sonic-vs.gz
-              mv target/docker-sonic-vs.gz target/docker-sonic-vs-asan.gz
+              make $BUILD_OPTIONS ENABLE_ASAN=y target/docker-sonic-vs.gz || true
+              mv target/docker-sonic-vs.gz target/docker-sonic-vs-asan.gz || true
+
             fi
             if [ "$(K8S_MASTER_CHANGED)" == 'YES' ]; then
               make $BUILD_OPTIONS INCLUDE_KUBERNETES_MASTER=y target/sonic-vs.img.gz
@@ -167,6 +185,11 @@ jobs:
               SONIC_RUN_CMDS="qemu-img convert target/sonic-vs.img -O vhdx -o subformat=dynamic target/sonic-vs.vhdx" make $BUILD_OPTIONS sonic-slave-run
               rm target/sonic-vs.img
             fi
+
+            #OUTPUT_BASE=$(bazel $(BAZEL_OPTS) info output_base)
+            #ls -la $OUTPUT_BASE/external/sonic_swss_common/common/ || true
+            #ls -lh src/sonic-swss-common/common | grep cfg || true
+
           elif [ $(GROUP_NAME) == vpp ]; then
             if [ $(dbg_image) == yes ]; then
               make $BUILD_OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-vpp.img.gz
